version: "3"

volumes:
  pgdb:

services:
  postgres:
    container_name: ${SERVICE_BACKEND_POSTGRESS}
    image: postgres:latest
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - env/dev/backend-db.env
    ports:
      - ${PORT_BACKEND_POSTGRESS}:5432
    networks:
      - ${NETWORK}


  mongo:
    container_name: ${SERVICE_MONGO}
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - ${NETWORK}


  backend:
    container_name: ${SERVICE_NEST}
    image: node:16.19.0-alpine3.16
    working_dir: /${FOLDER_NEST}
    volumes:
      - ./${FOLDER_NEST}:/${FOLDER_NEST}
      - ./${FOLDER_SHARED}:/${FOLDER_SHARED}
    env_file:
      - env/dev/.env
      - env/dev/backend.env
      - env/dev/backend-db.env
    ports:
      - ${PORT_NEST}:${PORT_NEST}
    networks:
      - ${NETWORK}
    command: ${COMMAND_BACKEND}
    links:
      - postgres
    depends_on:
      - postgres
    expose:
      - ${PORT_NEST}

  frontend:
    container_name: ${SERVICE_FRONTEND}
    image: node:19
    working_dir: /${FOLDER_VUE}
    volumes:
      - ./${FOLDER_VUE}:/${FOLDER_VUE}
      - ./${FOLDER_SHARED}:/${FOLDER_SHARED}
    ports:
      - ${PORT_FRONTEND}:${PORT_FRONTEND}
    networks:
      - ${NETWORK}
    command: ${COMMAND_FRONTEND}
    links:
      - backend

networks:
  postgres:
    driver: ${NETWORK_DRIVER}

