version: "3"

volumes:
  pgdb:

services:
  postgres:
    container_name: life_postgres
    image: postgres:latest
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - env/backend-db.env
    networks:
      - postgres

  pgadmin:
    container_name: life_pgadmin
    image: dpage/pgadmin4
    ports:
      - "9000:80"
    links:
      - postgres:postgres
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - env/backend-db.env
    networks:
      - postgres

  backend:
    image: node:14.16.0-alpine3.10
    container_name: life_nest
    working_dir: /life_nest
    ports:
      - "3000:3000"
    volumes:
      - ../life_nest:/life_nest:cached
    links:
      - postgres:postgres
    env_file:
      - env/backend-db.env
      - env/backend.env
    networks:
      - postgres
    depends_on:
      - postgres
    command: sh -c "npm run start:dev"
    expose:
      - "3000"

  frontend:
    image: node:14.16.0-alpine3.10
    container_name: life_frontend
    working_dir: /life_frontend
    build:
      context: ../life_frontend
    ports:
      - "8080:8080"
    volumes:
      - ../life_frontend:/life_frontend:cached
    networks:
      - postgres
    command: sh -c "npm run serve"
    links:
      - backend

  sentry-redis:
    image: redis

  sentry-postgres:
    container_name: life_sentry_postgress
    image: postgres
    volumes:
      - pgdb:/var/lib/postgresql/data
    env_file:
      - env/sentry.env

  sentry-sentry:
    container_name: life_sentry
    image: sentry
    links:
      - sentry-redis
      - sentry-postgres
    ports:
      - 9001:9000
    env_file:
      - env/sentry.env
      - env/sentry-db.env

  sentry-cron:
    container_name: life_sentry_cron
    image: sentry
    links:
      - sentry-redis
      - sentry-postgres
    command: "sentry run cron"
    env_file:
      - env/sentry.env
      - env/sentry-db.env

  sentry-worker:
    container_name: life_sentry_worker
    image: sentry
    links:
      - sentry-redis
      - sentry-postgres
    command: "sentry run worker"
    env_file:
      - env/sentry.env
      - env/sentry-db.env

networks:
  postgres:
    driver: bridge

